"""ADK server variant — SPEC.md §6, Milestone 1 (google-adk 2.8.0, mcp 1.29.1).

The world operations are defined as ADK-native ``FunctionTool`` objects
(the exact tool objects an ADK agent calls) and hosted on an ``LlmAgent``.
They are then exposed over MCP stdio with the M1 contract identical to the
official-SDK variant: same tools, same parameter names and field
descriptions, same resource, same prompt. M2.1 adds a sixth FunctionTool,
``probe_schema`` (SPEC.md §8 SCHEMA echo probe), registered the same way.
M2.3a adds a seventh, ``create_ticket`` (SPEC.md §21 idempotent creation),
plus the shared deterministic fault layer (mcp_sdk_bench.faults), driven by
env vars read once at startup — identical semantics to the other variants.

Deviation note (recorded per AGENTS.md §5 honesty rules): ADK 2.8's only
agent-as-MCP-server path is ``to_mcp_server`` in the private module
``google.adk.tools.mcp_tool._agent_to_mcp`` (marked
``@experimental(FeatureName.MCP_AGENT_SERVER)``). It exposes the whole agent
as ONE conversational MCP tool, so it cannot express the M1 contract of five
named tools plus a resource and a prompt. This variant therefore serves the
agent's individual ``FunctionTool`` definitions through
``mcp.server.fastmcp.FastMCP`` — the same serving surface ADK itself uses in
``_agent_to_mcp`` — pinned at mcp 1.29.1 in envs/adk (``google-adk[mcp]``
requires mcp 1.x; DECISIONS.md D1). The ``mcp.server.fastmcp`` imports carry
``ty: ignore[unresolved-import]`` because the main env pins mcp 2.x, which
renamed that module; this module only ever executes inside envs/adk.

Two ADK 2.8 findings baked in below:
- ``FunctionTool`` derives name/description from the wrapped function's
  ``__name__``/docstring, so each tool's docstring IS its contract
  description. Its declaration builder also drops ``Field(description=...)``
  metadata, so the MCP-side schema (generated by FastMCP from the same
  annotated signature) is the one that carries field descriptions.
- mcp 1.x FastMCP wraps any tool exception as
  ``ToolError("Error executing tool <name>: <message>")``; the WorldError
  text is always included, and the result is ``isError=True`` — never a
  crash.

M3.1 (SPEC.md §18) capability classification: NO protocol elicitation, and
none is stubbed. The tools below are ADK ``FunctionTool`` definitions served
through mcp 1.x FastMCP — there is no request-context injection point at
which a FunctionTool could suspend on an MCP ``elicitation/create`` exchange,
so ``reserve_inventory`` keeps raising WorldError on a missing employee and
``deploy_service`` keeps the legacy production guard. (Verified in envs/adk:
ADK 2.8.0's ``McpToolset`` accepts an ``elicitation_callback`` on the CLIENT
side, but wiring it would change the harness for one candidate only —
SPEC.md §23 one-independent-variable — and the server side still cannot
reach it from a FunctionTool.) Framework-native equivalents exist outside
MCP: ``FunctionTool(require_confirmation=...)`` (HITL confirmation inside
the ADK runtime) and ``LongRunningFunctionTool`` (async long-running tools).
They are documented in docs/capability-matrix.md and deliberately NOT wired
into this variant. ``employee_id`` becomes optional in the schema (identical
change in all three variants) so the missing-employee flow reaches the
world's honest WorldError instead of a schema-validation error.

M3.2 (SPEC.md §17 Tasks): the mcp 1.29.1 FastMCP serving surface exposes NO
Tasks methods (no task request handlers, no task-capable client surface in
ADK's McpToolset), so the three tools below (generate_monthly_report /
get_report_task / cancel_report_task) are the APP-LEVEL equivalent — the
same world task registry driven by plain tool calls, classified as such in
docs/capability-matrix.md, never as protocol tasks. The framework-native
long-running abstraction exists outside MCP: ADK 2.8.0 ships
``google.adk.tools.LongRunningFunctionTool`` (verified in envs/adk). It is
documented in the capability matrix and deliberately NOT wired into this
variant (it would change the harness for one candidate only — SPEC.md §23).
Like the other variants, the task tools bypass run_tool_with_faults by
design: the M3.2 fault story is the world's asynchronous mid-task failure
(one FaultEngine.task_failure() draw at task start, applied at the first
progress tick).

This module runs only in the ADK env. From the repo root:

    PYTHONPATH=src uv run --project envs/adk python -m mcp_sdk_bench.servers.adk

Smoke self-check (spawns the server over stdio, lists tools, exits 0):

    PYTHONPATH=src uv run --project envs/adk python -m mcp_sdk_bench.servers.adk --smoke
"""
from __future__ import annotations

import inspect
from collections.abc import Awaitable, Callable
from enum import Enum
from typing import Annotated, Any, TypeVar, cast, overload

from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from mcp.server.fastmcp import FastMCP  # ty: ignore[unresolved-import]
from mcp.server.fastmcp.exceptions import ToolError  # ty: ignore[unresolved-import]
from pydantic import BaseModel, Field

from mcp_sdk_bench.faults import (
    FaultEngine,
    InjectedToolFault,
    load_fault_config,
    run_tool_with_faults,
)
from mcp_sdk_bench.world import (
    Deployment,
    InventoryItem,
    ProbeNestedItem,
    ProbeNestedObject,
    ReportTaskView,
    Ticket,
    TicketStatus,
    World,
    WorldError,
    load_task_tick_s,
    report_task_view,
    reset_world,
)

SERVER_NAME = "mcp-sdk-bench-adk"
SERVER_VERSION = "0.1.0"

# LlmAgent names must be valid Python identifiers (ADK 2.8 validation).
AGENT_NAME = "mcp_sdk_bench_adk"
# Placeholder model id: the agent is never run server-side (MCP calls go
# straight to the FunctionTools), so no model API call is ever made here.
AGENT_MODEL = "gemini-2.5-flash"

DEPLOYMENT_POLICY_URI = "company://policies/deployment"
DEPLOYMENT_POLICY_DOC_ID = "dep-policy"
INCIDENT_TRIAGE_PROMPT = "incident-triage"


# ---- tool output models (drive both structuredContent and outputSchema) ----


class TicketOutput(BaseModel):
    ticket: Ticket


class InventoryOutput(BaseModel):
    items: dict[str, InventoryItem]


class ReserveInventoryOutput(BaseModel):
    item: InventoryItem


class DeploymentOutput(BaseModel):
    deployment: Deployment


class ProbeSchemaOutput(BaseModel):
    received: dict[str, Any]
    count: int


class ReportTaskOutput(BaseModel):
    """M3.2 app-level task view envelope (identical across variants)."""

    task: ReportTaskView


class SchemaEnum(str, Enum):
    """Enum for probe_schema.enum_field (mirrors the FastMCP variant).
    Verified against installed ADK 2.8.0: FunctionTool accepts a str-Enum
    parameter and emits a $defs-referenced string enum schema."""

    ALPHA = "alpha"
    BETA = "beta"
    GAMMA = "gamma"


_T = TypeVar("_T")


def _incident_triage_text(ticket_id: str) -> str:
    return (
        f"You are triaging incident ticket {ticket_id}. Follow these steps in order:\n"
        f"1. Inspect the ticket by calling the get_ticket tool with ticket_id \"{ticket_id}\".\n"
        f"2. Retrieve the deployment policy by reading the resource {DEPLOYMENT_POLICY_URI}.\n"
        "3. Identify the owning team from the ticket's team field.\n"
        "4. Inspect the owning team's deployment state for the services that team owns.\n"
        "5. Produce a recommendation for the next action, citing the policy constraints "
        "that apply."
    )


def build_agent(world: World) -> LlmAgent:
    """Build the ADK agent hosting the world operations as FunctionTools.

    Tool docstrings are the contract descriptions — ADK's FunctionTool reads
    name/description from the wrapped function. Fault config is read from the
    environment once, here, at agent build (= server startup, SPEC.md §21).
    """
    fault_engine = FaultEngine(load_fault_config())

    @overload
    async def _run(
        execute: Callable[[], Awaitable[_T]],
        *,
        is_replay: Callable[[], bool] = ...,
    ) -> _T: ...

    @overload
    async def _run(
        execute: Callable[[], _T],
        *,
        is_replay: Callable[[], bool] = ...,
    ) -> _T: ...

    async def _run(
        execute: Callable[[], _T | Awaitable[_T]],
        *,
        is_replay: Callable[[], bool] = lambda: False,
    ) -> _T:
        """Shared dispatch through the deterministic fault layer (SPEC.md
        §21); identical semantics to the other two server variants. Execute
        thunks may be async (M3.1)."""
        async def settled() -> _T:
            value = execute()
            if inspect.isawaitable(value):
                return await cast("Awaitable[_T]", value)
            return cast("_T", value)

        try:
            return await run_tool_with_faults(fault_engine, settled, is_replay=is_replay)
        except (InjectedToolFault, WorldError) as err:
            raise ToolError(str(err)) from err

    async def get_ticket(
        ticket_id: Annotated[str, Field(description="Ticket identifier, e.g. PAY-123")],
    ) -> TicketOutput:
        """Fetch a single ticket by id."""
        return await _run(lambda: TicketOutput(ticket=world.get_ticket(ticket_id)))

    async def update_ticket(
        ticket_id: Annotated[str, Field(description="Ticket identifier, e.g. PAY-123")],
        status: Annotated[
            TicketStatus | None,
            Field(description="New ticket status; omit to leave unchanged"),
        ] = None,
        assignee: Annotated[
            str | None,
            Field(description="Employee id to assign; omit to leave unchanged"),
        ] = None,
    ) -> TicketOutput:
        """Update a ticket's status and/or assignee."""
        return await _run(
            lambda: TicketOutput(ticket=world.update_ticket(ticket_id, status, assignee))
        )

    async def create_ticket(
        ticket_id: Annotated[str, Field(description="Ticket identifier to create, e.g. T-1")],
        title: Annotated[str, Field(description="Ticket title")],
        idempotency_key: Annotated[
            str,
            Field(
                description="Idempotency key; a retry with the same key returns the existing ticket"
            ),
        ],
        priority: Annotated[
            str | None, Field(description="Ticket priority, e.g. high; omit for none")
        ] = None,
    ) -> TicketOutput:
        """Create a ticket; idempotent on idempotency_key (SPEC.md §21)."""
        return await _run(
            lambda: TicketOutput(
                ticket=world.create_ticket(
                    ticket_id, title, priority, idempotency_key=idempotency_key
                )
            ),
            is_replay=lambda: world.ticket_for_idempotency_key(idempotency_key) is not None,
        )

    async def get_inventory() -> InventoryOutput:
        """List all inventory items with availability."""
        return await _run(lambda: InventoryOutput(items=world.get_inventory()))

    async def reserve_inventory(
        item: Annotated[str, Field(description="Inventory item name, e.g. thinkpad-t14")],
        employee_id: Annotated[
            str | None,
            Field(
                description=(
                    "Employee id making the reservation, e.g. alice; omit when unknown "
                    "— the server will ask the user (elicitation)"
                )
            ),
        ] = None,
    ) -> ReserveInventoryOutput:
        """Reserve one unit of an inventory item for an employee."""

        # M3.1: no elicit callback — the ADK variant has no protocol
        # elicitation surface, so a missing employee raises the world's
        # honest WorldError (see module docstring).
        async def execute() -> ReserveInventoryOutput:
            return ReserveInventoryOutput(item=await world.reserve_inventory(item, employee_id))

        return await _run(execute)

    async def deploy_service(
        service: Annotated[str, Field(description="Service name, e.g. checkout")],
        target_version: Annotated[str, Field(description="Version to deploy, e.g. 1.8.3")],
        environment: Annotated[
            str, Field(description="Target environment, e.g. staging or production")
        ],
    ) -> DeploymentOutput:
        """Deploy a service at a target version to an environment."""

        # M3.1: no elicit callback — the legacy production guard applies.
        async def execute() -> DeploymentOutput:
            return DeploymentOutput(
                deployment=await world.deploy_service(service, target_version, environment)
            )

        return await _run(execute)

    async def probe_schema(
        string_field: str,
        int_field: int,
        float_field: float,
        bool_field: bool,
        enum_field: SchemaEnum,
        nullable_field: str | None,
        union_field: str | int,
        list_field: list[str],
        nested_field: ProbeNestedObject,
        nested_list_field: list[ProbeNestedItem],
    ) -> ProbeSchemaOutput:
        """Side-effect-free echo probe exercising every JSON-schema primitive (SPEC.md §8 SCHEMA)."""
        return await _run(
            lambda: ProbeSchemaOutput(
                **world.probe_schema(
                    string_field=string_field,
                    int_field=int_field,
                    float_field=float_field,
                    bool_field=bool_field,
                    enum_field=enum_field.value,
                    nullable_field=nullable_field,
                    union_field=union_field,
                    list_field=list_field,
                    nested_field=nested_field,
                    nested_list_field=nested_list_field,
                )
            )
        )

    async def generate_monthly_report() -> ReportTaskOutput:
        """Start a simulated monthly-report task; returns the task handle and initial status (app-level task equivalent, SPEC.md §17)."""
        # Bypasses the synchronous fault layer by design (module docstring).
        try:
            task = await world.start_report_task(fault_engine)
        except WorldError as err:
            raise ToolError(str(err)) from err
        return ReportTaskOutput(task=report_task_view(task))

    async def get_report_task(
        handle: Annotated[
            str, Field(description="Task handle returned by generate_monthly_report")
        ],
    ) -> ReportTaskOutput:
        """Poll a report task by handle; returns status and progress (app-level tasks/get equivalent, SPEC.md §17)."""
        try:
            task = world.get_report_task(handle)
        except WorldError as err:
            raise ToolError(str(err)) from err
        return ReportTaskOutput(task=report_task_view(task))

    async def cancel_report_task(
        handle: Annotated[
            str, Field(description="Task handle returned by generate_monthly_report")
        ],
    ) -> ReportTaskOutput:
        """Cancel a running report task by handle (app-level tasks/cancel equivalent, SPEC.md §17)."""
        try:
            task = await world.cancel_report_task(handle)
        except WorldError as err:
            raise ToolError(str(err)) from err
        return ReportTaskOutput(task=report_task_view(task))

    tools = [
        FunctionTool(func=fn)
        for fn in (
            get_ticket,
            update_ticket,
            create_ticket,
            get_inventory,
            reserve_inventory,
            deploy_service,
            probe_schema,
            generate_monthly_report,
            get_report_task,
            cancel_report_task,
        )
    ]
    return LlmAgent(
        name=AGENT_NAME,
        model=AGENT_MODEL,
        description="M1 benchmark world agent (tools served over MCP, never run by a model here).",
        tools=tools,
    )


def create_server() -> FastMCP:
    """Build the ADK M1 server. A fresh seeded World is created here, so each
    server process owns exactly one in-memory world instance."""
    world: World = reset_world()
    # M3.2: no update_hook — no server-pushed task notification surface on
    # the mcp 1.x FastMCP serving path; clients poll (app-level).
    world.set_task_runtime(tick_s=load_task_tick_s())
    agent = build_agent(world)
    # mcp 1.x FastMCP has no `version` kwarg (unlike FastMCP 4.x); the server
    # version is kept as a module constant for results/environment.json.
    server = FastMCP(SERVER_NAME)

    # Serve each ADK FunctionTool as an MCP tool. The FunctionTool is the
    # definition of record for name/description; FastMCP regenerates the
    # input/output schemas from the same annotated signature.
    for adk_tool in agent.tools:
        assert isinstance(adk_tool, FunctionTool)
        server.add_tool(adk_tool.func, name=adk_tool.name, description=adk_tool.description)

    @server.resource(
        DEPLOYMENT_POLICY_URI,
        name="deployment-policy",
        title="Deployment Policy",
        description="Company deployment policy (approvals, rollout plans, change freezes).",
        mime_type="text/markdown",
    )
    def deployment_policy() -> str:
        doc = world.documents[DEPLOYMENT_POLICY_DOC_ID]
        return f"# {doc.title}\n\n{doc.body}"

    @server.prompt(name=INCIDENT_TRIAGE_PROMPT, description="Triage an incident ticket against the deployment policy.")
    def incident_triage(
        ticket_id: Annotated[
            str, Field(description="Ticket identifier to triage, e.g. PAY-123")
        ],
    ) -> str:
        return _incident_triage_text(ticket_id)

    return server
