"""ADK server variant — SPEC.md §6, Milestone 1 (google-adk 2.8.0, mcp 1.29.1).

The five world operations are defined as ADK-native ``FunctionTool`` objects
(the exact tool objects an ADK agent calls) and hosted on an ``LlmAgent``.
They are then exposed over MCP stdio with the M1 contract identical to the
official-SDK variant: same 5 tools, same parameter names and field
descriptions, same resource, same prompt.

Deviation note (recorded per AGENTS.md §5 honesty rules): ADK 2.8's only
agent-as-MCP-server path is ``to_mcp_server`` in the private module
``google.adk.tools.mcp_tool._agent_to_mcp`` (marked
``@experimental(FeatureName.MCP_AGENT_SERVER)``). It exposes the whole agent
as ONE conversational MCP tool, so it cannot express the M1 contract of five
named tools plus a resource and a prompt. This variant therefore serves the
agent's individual ``FunctionTool`` definitions through
``mcp.server.fastmcp.FastMCP`` — the same serving surface ADK itself uses in
``_agent_to_mcp`` — pinned at mcp 1.29.1 in envs/adk (``google-adk[mcp]``
requires mcp 1.x; DECISIONS.md D1). The ``mcp.server.fastmcp`` imports carry
``ty: ignore[unresolved-import]`` because the main env pins mcp 2.x, which
renamed that module; this module only ever executes inside envs/adk.

Two ADK 2.8 findings baked in below:
- ``FunctionTool`` derives name/description from the wrapped function's
  ``__name__``/docstring, so each tool's docstring IS its contract
  description. Its declaration builder also drops ``Field(description=...)``
  metadata, so the MCP-side schema (generated by FastMCP from the same
  annotated signature) is the one that carries field descriptions.
- mcp 1.x FastMCP wraps any tool exception as
  ``ToolError("Error executing tool <name>: <message>")``; the WorldError
  text is always included, and the result is ``isError=True`` — never a
  crash.

This module runs only in the ADK env. From the repo root:

    PYTHONPATH=src uv run --project envs/adk python -m mcp_sdk_bench.servers.adk

Smoke self-check (spawns the server over stdio, lists tools, exits 0):

    PYTHONPATH=src uv run --project envs/adk python -m mcp_sdk_bench.servers.adk --smoke
"""
from __future__ import annotations

from typing import Annotated

from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from mcp.server.fastmcp import FastMCP  # ty: ignore[unresolved-import]
from mcp.server.fastmcp.exceptions import ToolError  # ty: ignore[unresolved-import]
from pydantic import BaseModel, Field

from mcp_sdk_bench.world import (
    Deployment,
    InventoryItem,
    Ticket,
    TicketStatus,
    World,
    WorldError,
    reset_world,
)

SERVER_NAME = "mcp-sdk-bench-adk"
SERVER_VERSION = "0.1.0"

# LlmAgent names must be valid Python identifiers (ADK 2.8 validation).
AGENT_NAME = "mcp_sdk_bench_adk"
# Placeholder model id: the agent is never run server-side (MCP calls go
# straight to the FunctionTools), so no model API call is ever made here.
AGENT_MODEL = "gemini-2.5-flash"

DEPLOYMENT_POLICY_URI = "company://policies/deployment"
DEPLOYMENT_POLICY_DOC_ID = "dep-policy"
INCIDENT_TRIAGE_PROMPT = "incident-triage"


# ---- tool output models (drive both structuredContent and outputSchema) ----


class TicketOutput(BaseModel):
    ticket: Ticket


class InventoryOutput(BaseModel):
    items: dict[str, InventoryItem]


class ReserveInventoryOutput(BaseModel):
    item: InventoryItem


class DeploymentOutput(BaseModel):
    deployment: Deployment


def _incident_triage_text(ticket_id: str) -> str:
    return (
        f"You are triaging incident ticket {ticket_id}. Follow these steps in order:\n"
        f"1. Inspect the ticket by calling the get_ticket tool with ticket_id \"{ticket_id}\".\n"
        f"2. Retrieve the deployment policy by reading the resource {DEPLOYMENT_POLICY_URI}.\n"
        "3. Identify the owning team from the ticket's team field.\n"
        "4. Inspect the owning team's deployment state for the services that team owns.\n"
        "5. Produce a recommendation for the next action, citing the policy constraints "
        "that apply."
    )


def build_agent(world: World) -> LlmAgent:
    """Build the ADK agent hosting the five world operations as FunctionTools.

    Tool docstrings are the contract descriptions — ADK's FunctionTool reads
    name/description from the wrapped function.
    """

    def get_ticket(
        ticket_id: Annotated[str, Field(description="Ticket identifier, e.g. PAY-123")],
    ) -> TicketOutput:
        """Fetch a single ticket by id."""
        try:
            return TicketOutput(ticket=world.get_ticket(ticket_id))
        except WorldError as err:
            raise ToolError(str(err)) from err

    def update_ticket(
        ticket_id: Annotated[str, Field(description="Ticket identifier, e.g. PAY-123")],
        status: Annotated[
            TicketStatus | None,
            Field(description="New ticket status; omit to leave unchanged"),
        ] = None,
        assignee: Annotated[
            str | None,
            Field(description="Employee id to assign; omit to leave unchanged"),
        ] = None,
    ) -> TicketOutput:
        """Update a ticket's status and/or assignee."""
        try:
            return TicketOutput(ticket=world.update_ticket(ticket_id, status, assignee))
        except WorldError as err:
            raise ToolError(str(err)) from err

    def get_inventory() -> InventoryOutput:
        """List all inventory items with availability."""
        return InventoryOutput(items=world.get_inventory())

    def reserve_inventory(
        item: Annotated[str, Field(description="Inventory item name, e.g. thinkpad-t14")],
        employee_id: Annotated[
            str, Field(description="Employee id making the reservation, e.g. alice")
        ],
    ) -> ReserveInventoryOutput:
        """Reserve one unit of an inventory item for an employee."""
        try:
            return ReserveInventoryOutput(item=world.reserve_inventory(item, employee_id))
        except WorldError as err:
            raise ToolError(str(err)) from err

    def deploy_service(
        service: Annotated[str, Field(description="Service name, e.g. checkout")],
        target_version: Annotated[str, Field(description="Version to deploy, e.g. 1.8.3")],
        environment: Annotated[
            str, Field(description="Target environment, e.g. staging or production")
        ],
    ) -> DeploymentOutput:
        """Deploy a service at a target version to an environment."""
        try:
            return DeploymentOutput(
                deployment=world.deploy_service(service, target_version, environment)
            )
        except WorldError as err:
            raise ToolError(str(err)) from err

    tools = [
        FunctionTool(func=fn)
        for fn in (get_ticket, update_ticket, get_inventory, reserve_inventory, deploy_service)
    ]
    return LlmAgent(
        name=AGENT_NAME,
        model=AGENT_MODEL,
        description="M1 benchmark world agent (tools served over MCP, never run by a model here).",
        tools=tools,
    )


def create_server() -> FastMCP:
    """Build the ADK M1 server. A fresh seeded World is created here, so each
    server process owns exactly one in-memory world instance."""
    world: World = reset_world()
    agent = build_agent(world)
    # mcp 1.x FastMCP has no `version` kwarg (unlike FastMCP 4.x); the server
    # version is kept as a module constant for results/environment.json.
    server = FastMCP(SERVER_NAME)

    # Serve each ADK FunctionTool as an MCP tool. The FunctionTool is the
    # definition of record for name/description; FastMCP regenerates the
    # input/output schemas from the same annotated signature.
    for adk_tool in agent.tools:
        assert isinstance(adk_tool, FunctionTool)
        server.add_tool(adk_tool.func, name=adk_tool.name, description=adk_tool.description)

    @server.resource(
        DEPLOYMENT_POLICY_URI,
        name="deployment-policy",
        title="Deployment Policy",
        description="Company deployment policy (approvals, rollout plans, change freezes).",
        mime_type="text/markdown",
    )
    def deployment_policy() -> str:
        doc = world.documents[DEPLOYMENT_POLICY_DOC_ID]
        return f"# {doc.title}\n\n{doc.body}"

    @server.prompt(name=INCIDENT_TRIAGE_PROMPT, description="Triage an incident ticket against the deployment policy.")
    def incident_triage(
        ticket_id: Annotated[
            str, Field(description="Ticket identifier to triage, e.g. PAY-123")
        ],
    ) -> str:
        return _incident_triage_text(ticket_id)

    return server
